/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

var sumEvenFib = function(n) {
  var total = 0;

  // Recursively find fibonacci numbers from 1 to n
  var recurse = function(val1, val2) {
    if(val2 > n){
      return;
    }

    // If value is even
    if((val1 + val2) % 2 === 0) {
      // Add value to total
      total += val1 + val2;
    }

    recurse(val2, val1 + val2);
  };

  recurse(1, 1);

  // Return total
  return total;
};
